specfile_path: python-simpleline.spec
upstream_package_name: simpleline
actions:
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make BUILD_ARGS=sdist archive"
    - 'cp dist/*.tar.gz .'
    - 'ls *.tar.gz'
  fix-spec-file:
    - 'make bumpver'
jobs:
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: fedora-all

  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
